checks:
    php:
        code_rating: true
        duplication: true
filter:
    excluded_paths:
        - 'vendor/*'
    paths: {  }
tools:
    php_cpd:
        enabled: true
        command: phpcpd
        excluded_dirs: {  }
        names:
            - '*.php'
        min_lines: 5
        min_tokens: 70
        filter:
            excluded_paths:
                - 'vendor/*'
            paths: {  }
    php_pdepend:
        excluded_dirs:
            - vendor
        enabled: true
        command: pdepend
        configuration_file: null
        suffixes:
            - php
changetracking:
    bug_patterns:
        - '\bfix(?:es|ed)?\b'
    feature_patterns:
        - '\badd(?:s|ed)?\b'
        - '\bimplement(?:s|ed)?\b'